### ISSUE TITLE
Feature Request: Handle presence of byte order marking

### ISSUE THREAD

**Issue by dowlingw** [APIDevTools/json-schema-ref-parser#109]
According to RFC 7159, documents with a byte order mark are not valid JSON:
https://tools.ietf.org/html/rfc7159#section-8.1

>    Implementations MUST NOT add a byte order mark to the beginning of a
>    JSON text.  In the interests of interoperability, implementations
>    that parse JSON texts MAY ignore the presence of a byte order mark
>    rather than treating it as an error.

However, there are a number of notable specifications published that violate the standard.
Example: https://github.com/Azure/azure-resource-manager-schemas

It is currently possible to work around this by wrapping the inbuilt JSON parser with a custom parser that strips the offending characters.

Suggesting that this might be common enough that it's worth adding a flag to the JSON parser to handle this until the upstream sources are able to revise their specifications.

**Comment by JamesMessinger** [comment]
Great point!  I definitely think this should be built-in functionality.   I'd gladly accept a PR to add this.

**Comment by dowlingw** [comment]
Thanks, I've got the code to do this ready to go - will throw some tests around it and put together a PR as soon as possible, thanks!

**Comment by jonluca** [comment]
Added this feature to v11
