### ISSUE TITLE
Can we use Database ref in $ref

### ISSUE THREAD

**Issue by RS-Roshi** [APIDevTools/json-schema-ref-parser#111]
My question is that can we use a database reference inside $ref and does this library resolve the database reference easily???

**Comment by JamesMessinger** [comment]
Yes you can create your own [*custom resolver*](https://apidevtools.org/json-schema-ref-parser/docs/plugins/resolvers.html) to resolve any type of `$ref` you want.  The example on that page shows a simplistic MongoDB resolver.
