### ISSUE TITLE
Recursive external $ref gets resolved to itself when `bundle`

### ISSUE THREAD

**Issue by RomanHotsiy** [APIDevTools/json-schema-ref-parser#112]
Input:

```yaml
openapi: 3.0.2
info:
  version: 1.0.0
  title: Reproduction sample
  description: OpenAPI sample that exposes the problem
paths:
  /:
    get:
      description: get
      responses:
        default:
          description: response
          content: {}
components:
  schemas:
    Link:
      $ref: https://json-schema.org/draft-04/hyper-schema#/definitions/linkDescription
```

Code:

```js
const parser = new JsonSchemaRefParser();
const spec = await parser.bundle(spec);
```

Output:
```yaml
openapi: 3.0.2
info:
  version: 1.0.0
  title: Reproduction sample
  description: OpenAPI sample that exposes the problem
paths:
  "/":
    get:
      description: get
      responses:
        default:
          description: response
          content: {}
components:
  schemas:
    Link: # see bellow
      "$ref": "#/components/schemas/Link/properties/schema/properties/not/definitions/linkDescription"

It most likely has something to do with the fact that the ref is recursive.

**Comment by JamesMessinger** [comment]
Weird.  Thanks for reporting it.  Will investigate.

**Comment by medfreeman** [comment]
It is also true with the ´dereference´ method while using the ´circular: 'ignore'´ option.

**Comment by EricMCornelius** [comment]
Just hit this issue on a much much more complicated example.

Any investigation happening on it?

The similarity to my case is that I'm trying to bundle a schema which contains a reference to a fragment that contains a recursive reference, as above.

`$ref: https://json-schema.org/draft-04/hyper-schema`**#/definitions/linkDescription**

**Comment by EricMCornelius** [comment]
Note that if I reference the entire schema without the fragment, then the referenced schema with recursive elements is bundled without issue.

**Comment by romain-tracktik** [comment]
Just hit the same issue with a remote recursive $ref using bundle() I thought it was recursive-proof :D 
Do you guys have any update ?

**Comment by philsturgeon** [comment]
There are various types of circular reference and they usually need different code solutions, some of which are impossible to solve reasonably and can amount to user error. 

Maybe you could share the smallest recreate or example and we can see what’s up?

**Comment by romain-tracktik** [comment]
Sure, so here is the most basic example I can get :

`schema.json`
```json
{
  "type": "object",
  "properties": {
    "tree": {
      "title": "Recursive references",
      "$ref": "circular-definitions.json/#/definitions/node"
    }
  }
}

```

`circular-definitions.json`
```json
{
  "definitions": {
    "node": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/node"
          }
        }
      }
    }
  }
}
```

After applying bundle() I get the following : 
```json
{
  "type": "object",
  "properties": {
    "tree": {
      "title": "Recursive references",
      "$ref": "#/properties/tree/properties/children/items"
    }
  }
}
```

**Comment by philsturgeon** [comment]
@romain-tracktik thanks for the actual output, what was the expected output? How does what it's done differ from what you wanted?

**Comment by romain-tracktik** [comment]
On the actual output, the schema is not even correct as `#/properties/tree/properties/children/items ` doesn't exists on the result.

As it is stated for the bundle() method, I would have expected the remote definitions to have been imported into the schema, and the remote $ref replaced with a local $ref, something like :

```json
{
  "definitions": {
    "node": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/node"
          }
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "tree": {
      "title": "Recursive references",
      "$ref": "#/definitions/node"
    }
  }
}
```

**Comment by philsturgeon** [comment]
Ah, I believe your expectation of "definitions" being created is incorrect. It's going to pull the reference in once, then $ref to _that_. 

I think I see the bug here now though. The actual output should look a bit like this:

```json
{
  "type": "object",
  "properties": {
    "tree": {
      "title": "Recursive references",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/properties/tree"
          }
        }
      }
    }
  }
}
```

**Comment by romain-tracktik** [comment]
Hey @philsturgeon thank you for your answer, I didn't have time to come back on this sooner.

> I think I see the bug here now though. The actual output should look a bit like this:

```json
{
  "type": "object",
  "properties": {
    "tree": {
      "title": "Recursive references",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/properties/tree"
          }
        }
      }
    }
  }
}
```

I would be careful, here you are pointing to the root schema, whereas the original ref is pointing to another schema which is itself recursive.
For example here you add ` "title": "Recursive references"` from the root schema to every child, whereas in the original schema this title would only appear at the root. 

I would not be at ease using a method that change that much a schema just to include definitions.
At first thoughts I don't know if that could have side effects on a larger implementation with multiple $ref links from different files... just rising a flag. That would need to be tested with complex examples.

For your 2nd option, the problem is that we work on a pretty large definitions database, and we want to keep them separated, either to a large definitions file or to small separate files. This is only a basic example reproduction of the bug.

**Comment by philsturgeon** [comment]
I'm not sure what you mean, I wasn't offering options. The first code blog was how I would expect it to be resolved, as you were expecting a "definitions" to be created for you by json-schema-ref-resolver and that's not how it works. 

The second code block was me asking if you could try something out to see if it also created unexpected behavior. I was not at this point suggesting you change everything at your company. :)
