### ISSUE TITLE
Error: ENOTDIR: not a directory

### ISSUE THREAD

**Issue by tzachshabtay** [APIDevTools/json-schema-ref-parser#115]
My yaml file has a ref to a local file that looks like this:

`$ref: './common.yml/#/definitions/Status'`

When dereferencing, in parse.js, this line:

https://github.com/APIDevTools/json-schema-ref-parser/blob/bc3a14adb150bfeebee06ab49a209b1df522cdcd/lib/parse.js#L22

turns the path into `/<my_folder>/common.yml/` instead of `/<my_folder>/common.yml` (notice the slash at the end).

Then openfile (in file.js) throws an error (`ENOTDIR: not a directory`).

Ran from Ubuntu 18.04.

**Comment by JamesMessinger** [comment]
The problem here is that there's a trailing slash in your `$ref`.  Change it to this and it should work:

```yaml
$ref: common.yml#/definitions/Status
```
