### ISSUE TITLE
Contents of Bruce-Wayne.json

### ISSUE THREAD

**Issue by nilarte** [APIDevTools/json-schema-ref-parser#118]
I am having some difficulty about usage of Bruce-Wayne.json file in your example.
https://www.npmjs.com/package/json-schema-ref-parser
>>>>>

{
  "definitions": {
    "person": {
      // references an external file
      "$ref": "schemas/people/Bruce-Wayne.json"
    },
>>>>>>>>>

Can you send me content of this file please?

Help is really appreciated.

**Comment by JamesMessinger** [comment]
It could be any JSON content (an object, array, string, number, boolean, or null).  Most people use JSON References (`$ref`) to link to [JSON Schema](https://json-schema.org/learn/getting-started-step-by-step.html) files though, which would look something like this...

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/schemas/people/Bruce-Wayne.json",
  "title": "Bruce Wayne",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "default": "Bruce"
    },
    "lastName": {
      "type": "string",
      "default": "Wayne"
    },
    "alterEgo": {
      "type": "string",
      "default": "Batman"
    }
  }
}
```

**Comment by nilarte** [comment]
Thanks a ton @JamesMessinger 
This is exactly what I was looking for.

My earlier json was this.
>>>>
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"properties": {
	{"firstName": "Bruce"}
	}
}
>>>>
Just curious what I was missing mainly? "type"??

**Comment by nilarte** [comment]
Also closing issue since main purpose is served.
