### ISSUE TITLE
Version 6.1.0 changelog is missing

### ISSUE THREAD

**Issue by Kuraturpa** [APIDevTools/json-schema-ref-parser#127]
I'm seeing v6.0.0 in the CHANGELOG.md but not the latest v6.1.0 release
https://github.com/APIDevTools/json-schema-ref-parser/blob/master/CHANGELOG.md

**Comment by philsturgeon** [comment]
I've just set up semantic-release which will hopefully automatically publish changes to the CHANELOG.md, create GitHub Releases, and publish to NPM.
