### ISSUE TITLE
file.url in resolver is invalid

### ISSUE THREAD

**Issue by dawidgarus** [APIDevTools/json-schema-ref-parser#135]
When you use custom file resolver, say in bundle method:
```javascript
swaggerParser.bundle(spec, {
  parse: {
    json: true,
  },
  resolve: {
    file: {
      order: 1,
      canRead(file) {
        console.log(path.normalize(file.url));
        try {
          path.resolve(file.url);
          return true;
        } catch (e) {
          return false;
        }
      },
      read(file) {
        const relativePath = path.relative(process.cwd(), path.resolve(file.url));
        const fixedPath = path.join(specDir, relativePath);
        return fse.readFile(fixedPath, 'utf8');
      },
    },
  },
});
```
You get "%20" instead of space if path in `file.url` contains space.
The file.url should contain valid path that can be used with node's path module

**Comment by JamesMessinger** [comment]
Per the spec, all `$ref`s are URLs, not file paths.  So special characters (including spaces) are URL-encoded.  If you want to treat the URL as a file path, then you can decode it using `decodeURI()` or something similar.  Though I find that a better approach is to not use any spaces or special characters in my file names to avoid the problem altogether.

**Comment by dawidgarus** [comment]
But it's not an URL either, because it doesn't contain scheme: "c:\foo\bar" in not a valid URL.

**Comment by JamesMessinger** [comment]
It uses the base URL that you specify when calling `.bundle()`.  If you specify something like `C:\foo\bar` then that's the base URL, and all `$ref`s will be resolved relative to that.  If you want to use special characters (and thus, URL decoding), then I recommend that you specify a valid base URL, like `file://c/foo/bar` instead.
