### ISSUE TITLE
Error: Uncaught (in promise): ReferenceError: process is not defined

### ISSUE THREAD

**Issue by Adam-Michalski** [APIDevTools/json-schema-ref-parser#137]
Angular application

After instalation and when I declare variable

refParser = require('json-schema-ref-parser'); // <- when I add this line error occurs.

I get 

`Error: Uncaught (in promise): ReferenceError: process is not defined`

Is there something I am missing?

**Comment by JamesMessinger** [comment]
I'm guessing that you're using a bundler such as webpack, rollup, browserify, etc. and running your code in a web browser, correct?  If so, then you need to configure your bundler to use Node.js polyfills.  See [the ReadMe](https://github.com/APIDevTools/json-schema-ref-parser#browser-support) for links to additional information.

**Comment by sam3k** [comment]
> To use JSON Schema $Ref Parser in a browser, you'll need to use a bundling tool such as [Webpack](https://webpack.js.org/), [Rollup](https://rollupjs.org/), [Parcel](https://parceljs.org/), or [Browserify](http://browserify.org/). Some bundlers may require a bit of configuration, such as setting browser: true in [rollup-plugin-resolve](https://github.com/rollup/rollup-plugin-node-resolve).

Is there clear documentation on what needs to be configured in Webpack 5? 

I was getting: `Module not found: Can't resolve 'http'` which I've resolved by changing webpack config to:

```javascript
{
  ...
  resolve: {
    fallback: {
      http: false,
      https: false,
    }
  },
  ...
},
```

Now I'm getting `Uncaught ReferenceError: process is not defined` on `./node_modules/@apidevtools/swagger-parser/node_modules/@apidevtools/json-schema-ref-parser/lib/util/url.js`.

**Comment by starikovs** [comment]
For Vite I fixed it using this lib https://www.npmjs.com/package/vite-plugin-node-polyfills. I installed the lib and created a `vite.config.js` with the following contents:

```
import { defineConfig } from 'vite'
import { nodePolyfills } from 'vite-plugin-node-polyfills'

export default defineConfig({
  plugins: [
    nodePolyfills(),
  ],
});
```

Maybe that will be useful for somebody :)

**Comment by jswangtao** [comment]
> 对于 Vite，我使用此库https://www.npmjs.com/package/vite-plugin-node-polyfills修复了它。我安装了该库并创建了一个`vite.config.js`包含以下内容：
> 
> ```
> import { defineConfig } from 'vite'
> import { nodePolyfills } from 'vite-plugin-node-polyfills'
> 
> export default defineConfig({
>   plugins: [
>     nodePolyfills(),
>   ],
> });
> ```
> 
> 也许这对某些人有用:)

Don't work production build, but development mode it's work
