### ISSUE TITLE
Importing individual method fails with "Class is not a constructor"

### ISSUE THREAD

**Issue by silverwind** [APIDevTools/json-schema-ref-parser#139]
I'd like to import only the `dereference` method (the other parts of this module should ideally be tree-shaken out), but it seems this is currently not possible because of this error:

````js
> const {dereference} = require("json-schema-ref-parser")
> dereference({}).then(console.log)
Thrown:
TypeError: Class is not a constructor
    at $RefParser.dereference (node_modules/json-schema-ref-parser/lib/index.js:227:18)
````

Importing the default export works as expected in comparison:

````js
> const parser = require("json-schema-ref-parser")
> parser.dereference({}).then(console.log)
{}
````

**Comment by philsturgeon** [comment]
Is this code of any help? https://github.com/APIDevTools/json-schema-ref-parser/issues/14#issuecomment-698530729

**Comment by silverwind** [comment]
That example includes a path-based import which would break when the referenced file is moved. I would not consider it a stable interface.

**Comment by philsturgeon** [comment]
Yes this is a workaround not a complete solution.

**Comment by philsturgeon** [comment]
Anyone able to get a pull request over to fix this? Or is it not a problem anymore?
