### ISSUE TITLE
Can I keep definition root object after dereference?

### ISSUE THREAD

**Issue by francardoso93** [APIDevTools/json-schema-ref-parser#140]
If I have this object
`
"Name": {
					"type": "string",
					"description": "company description",
					"example": "Comercial",
				},
`

And it is referenced like 
`
"schema": {
								"$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/CampaignTypes_2_000.json#/definitions/Name"
							}
`

dereference() result will be:
`
"schema": {
					"type": "string",
					"description": "company description",
					"example": "Comercial",
		}
` (Root property key was lost)

Is there anyway I can keep the root property key "Name" saved somewhere?

**Comment by JamesMessinger** [comment]
I recommend adding a `title` to your schema for this.  It's a little redundant, but it's the only way to keep the "Name" value after dereferencing, and it's the recommended way of labeling schemas in both the JSON Schema and the OpenAPI specs.

So, in your case, you would change your object definition to this:

```
"Name": { "title": "Name", "type": "string", "description": "company description", "example": "Comercial", },
```
