### ISSUE TITLE
does not always terminate

### ISSUE THREAD

**Issue by miniHive** [APIDevTools/json-schema-ref-parser#143]
Using this wrapper tool https://github.com/davidkelley/json-dereference-cli,
it seems expansion of references does not always terminate, e.g. with

https://raw.githubusercontent.com/ProjectMarduk/Kanro/9d86bcfa673e6cb03d821012a593f9fae22a8865/schema/kanro.json

**Comment by jonluca** [comment]
This is fixed if using circular "ignore"
