### ISSUE TITLE
Cross referering if not working

### ISSUE THREAD

**Issue by Luci404** [APIDevTools/json-schema-ref-parser#148]
I have two schematics, person.json and qoute.json. 

The files are stored as so:
 - ./database/
    - people/person.json
    - quotes/qoute.json

content of person.json:
{
    "name": "Name Nameson",
    "qoutes": [
        {"$ref": "database/quotes/qoute.json#/qoute"}
    ]
}

content of qoute.json:
{
    "qoute": "Text Text Text Text"
    "author":  {"$ref": "database/people/person.json#/name"}
}

When i try to read the person.json file, i get a error of the qoute.json file. It basicaly says that is can't find the file at path "database/quotes/database/people.json"

And I'm not able to add "../../" to the path since i need to be able to read the file as a standaloen.,,

Is this a bug or how do i fix this problem?

**Comment by JamesMessinger** [comment]
This is the intended behavior.  According to the JSON Reference spec, `$ref`s are relative to the file that they're in.  In your case, you'd need to change the `$ref`s to look like this:

**person.json**

```json
{
  "name": "Name Nameson",
  "qoutes": [
    {"$ref": "qoute.json#/qoute"}
  ]
}
```

**qoute.json**

```json
{
  "qoute": "Text Text Text Text"
  "author": {"$ref": "person.json#/name"}
}
```
