### ISSUE TITLE
$RefParser.Options type info doesn't support custom resolvers

### ISSUE THREAD

**Issue by chriswa** [APIDevTools/json-schema-ref-parser#151]
$RefParser.Options.parse has [key: string], but $RefParser.Options.resolve does not.
The result is that and usage of custom resolvers will result in problems being reported by code intel and linting unless the user adds linting exceptions.

**Comment by chriswa** [comment]
Relevant docs describing usage here: https://github.com/APIDevTools/json-schema-ref-parser/blob/master/docs/plugins/resolvers.md

**Comment by chriswa** [comment]
Code demonstrating problem:
`await parser.bundle(inputFilepath, {
    resolve: {
      myResolver,
    },
  })`

**Comment by ahsan-babar** [comment]
@chriswa I'm not sure about how to use Custom Resolver while dereferencing. The example provided is not sufficient.
Do I have to make a pull request of my Custom Resolver? Or I can keep the Custom Resolver Locally somewhere in my code base.

My problem is:
I have a JSON schema having two different Http Server URLs as $ref. Both URLs/hosts(http://192.168.10.1:9200/data1, http://192.168.10.2:9200/data2) need separate Http Request headers for Authorization.

`dereference` only supports one header field. I want to make a custom resolver that take key-value pair of headers against URLs as argument and decides which headers should be used against the $ref URL.

`const JSONSchema = {
    "$schema": "http://json-schema.org/draft-07/schema#", "additionalProperties": false,
    "properties":
    {
        "data1": { "$ref": "http://192.168.10.1:9200/data1", "title": "data1" },
        "data2": { "$ref": "http://192.168.10.2:9200/data2", "title": "data2" },
    }, "required": ["data1", "data2"],
    "title": "data",
    "type": "object"
};`

I'll be grateful for your help.
