### ISSUE TITLE
npm ERR! missing script: build

### ISSUE THREAD

**Issue by huanyang01** [APIDevTools/json-schema-ref-parser#155]
Building/Testing
To build/test the project locally on your computer:

Clone this repo
git clone https://github.com/APIDevTools/json-schema-ref-parser.git

Install dependencies
npm install

Run the build script
npm run build

----------------------------------------------------------------------------

C:\GitHub\json-schema-ref-parser>npm run build
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:

**Comment by JamesMessinger** [comment]
Oh, good catch!  Sorry about that.  There is no build script for this project.  I'll update the ReadMe to remove that step.

Thanks!
