### ISSUE TITLE
Which npm package is the "official" one?

### ISSUE THREAD

**Issue by brentonhouse** [APIDevTools/json-schema-ref-parser#159]
I see that there are two npm packages published.  Which one is the "official" one?

https://www.npmjs.com/package/json-schema-ref-parser
https://www.npmjs.com/package/@apidevtools/json-schema-ref-parser

**Comment by JamesMessinger** [comment]
Hi Brenton! Remember me? I'm the organizer of the [Austin API Meetup](https://www.meetup.com/Austin-Homegrown-API/). I met you and Emmelyn at the Austin API Summit last year. 👋 

Anyway, to answer your question...  We are in the process of moving all of the API Dev Tools packages to the `@apidevtools` scope on NPM.  But to keep backward compatibility, we will also continue publishing the original un-scoped packages for a little while.  So, for now, both packages are exactly the same, but I encourage you to start using `@apidevtools/json-schema-ref-parser`

**Comment by brentonhouse** [comment]
Thanks @JamesMessinger !  Love this library!!
