### ISSUE TITLE
Inline dereferencing and fragments

### ISSUE THREAD

**Issue by nthsense** [APIDevTools/json-schema-ref-parser#17]
json-schema-ref-parser appears to not support a portion of the JSON Schema spec regarding inline dereferencing (see http://json-schema.org/latest/json-schema-core.html#anchor31)

Reproducer:
`
var test = {
    "id": "http://some.site/schema#",
    "not": { "$ref": "#inner" },
    "definitions": {
        "schema1": {
            "id": "#inner",
            "type": "boolean"
        }
    }
};

deref.dereference(test, function(err, schema){
    console.log(err, schema);
});
`

Output:

`
  "name": "SyntaxError",
  "message": "Invalid $ref pointer \"inner\". Pointers must begin with \"#/\"",
  "stack": "SyntaxError: Invalid $ref pointer \"inner\". Pointers must begin wit
h \"#/\"
`

I understand that this is not a required part of the spec, however it is a SHOULD given that the implementation does support inline dereferencing in general.

**Comment by BigstickCarpet** [comment]
Currently, JSON Schema $Ref Parser only supports [canonical dereferencing](http://json-schema.org/latest/json-schema-core.html#anchor30), as required by the JSON Schema spec.  Support for inline dereferencing is optional, and I haven't found much real-world demand for it, so it's not currently supported.  That said, if there's lots of demand for it, then I may add it in the future.

I'd also welcome a pull-request, if you feel like tackling this yourself.  As long as it doesn't break compatibility with any of the current canonical dereferencing functionality, I'd gladly accept it.  If you decide to give this a go, please fork the [4.0.0 branch](https://github.com/BigstickCarpet/json-schema-ref-parser/tree/releases/4.0.0), not the current 3.x branch.

**Comment by n1ywb** [comment]
Internal reference support is a should, however

> All fragment identifiers that do not match the JSON Pointer syntax MUST be interpreted as plain name fragment identifiers.

The program crashes with an error on valid schemas because of lack of adherence to this clause. If it's not going to support internal references, it should ignore them.

**Comment by BigstickCarpet** [comment]
I intend to support inline references in the next version of JSON Schema $Ref Parser, which I have already begun working on.  👍

**Comment by TJKoury** [comment]
@BigstickCarpet Are you still open to pull requests on this, or is it far enough that I can test it?  I really need [internal dereferencing](http://json-schema.org/latest/json-schema-core.html#rfc.section.9.2.1).

**Comment by BigstickCarpet** [comment]
Hi @TJKoury - I haven't had time to make any progress on this, but I'd be glad to accept a PR (especially if it also includes tests) 😉

**Comment by TJKoury** [comment]
@BigstickCarpet Thanks for the quick reply!  What branch should I work off of, were I to attempt this task?

**Comment by BigstickCarpet** [comment]
@TJKoury - Now that v4 has been released, you can just work off of the `master` branch

**Comment by Relequestual** [comment]
... so this means this issue is likely resolved and can be closed?
