### ISSUE TITLE
Omitting TypedArrays from crawling?

### ISSUE THREAD

**Issue by ntamas** [APIDevTools/json-schema-ref-parser#185]
I have recently run into an issue with `json-schema-ref-parser` on a JSON object that uses `$ref` pointers to binary assets that get merged into the JSON object as `Uint8Array`s. Some of these arrays are fairly large (several megabytes), and it turns out that the `crawl()` function in `lib/dereference.js` descends into every single element of these arrays even though they cannot contain `$ref` references to other items (since all the elements are numbers).

Would it be possible to exclude `TypedArray`s from the crawl? If so, would you be open to accepting a PR if I prepare one?

**Comment by JamesMessinger** [comment]
Yeah, I think that makes total sense. A PR would be appreciated 👍

**Comment by philsturgeon** [comment]
Fixed in #187.
