### ISSUE TITLE
can't save in original format

### ISSUE THREAD

**Issue by SamShekhovtsov** [APIDevTools/json-schema-ref-parser#188]
the biggest inconvenience is that it is impossible to save schema in the original YAML format. I can use JSON.stringify() - but that gives just a mess. The serialized object is not a JSON schema but a full mess. This makes this tool completely useless.

**Comment by philsturgeon** [comment]
Please post a constructive bug report with an example of what you’re trying to do, what the actual outcome was, and what the expected outcome was.
