### ISSUE TITLE
Vue cli 3 JSON schema loader with reference and pointer support

### ISSUE THREAD

**Issue by mgesmundo** [APIDevTools/json-schema-ref-parser#192]
Hello there,
to use this awesome module into a Vue application I created a simple webpack plugin to load all schemas and all references bundling all into a single JSON schema ready to import into a .vue file.

https://gist.github.com/mgesmundo/07d6ea3958ed4c7d19d1161551fa46ca

All the best.

**Comment by JamesMessinger** [comment]
Thanks for sharing!  That's a great usage of this library.
