### ISSUE TITLE
How to specify $ref base url?

### ISSUE THREAD

**Issue by Alain1405** [APIDevTools/json-schema-ref-parser#20]
I serve a frontend locally with node at `localhost:8000`. I pull the json schema from an API. 
The backend returning the json schema seats at `localhost:8888`  (`http://127.0.0.1:8888/api/controllers/schema`).

The schema has arrays of `$ref` fields in form of relative urls : 
`var schema = [{$ref:"/api/controllers/123"},{...}]`.

json-schema-ref-parser resolves references relatively to the frontend url rather than the backend url. `$RefParser.resolve(schema);` throws the following errors:
- `request.js:114 GET http://localhost:8000/api/controllers/123 404 (Not Found)` 
- `index.js:67 Uncaught (in promise) Error: Error downloading http://localhost:8000/api/controllers/123`. 

How can I pass `localhost:8888` to resolve as base url?

**Comment by Alain1405** [comment]
I've just realized that I can pass a url to the schema to resolve, in which case the $refs are resolved correctly, but yet this is not what I want. I pull the schema using AngularJs `$reource` service, which allows queries, sorting and pagination. Then I want to pass the resulting schema to the resolve method together with the base url of the api.

**Comment by Alain1405** [comment]
Here is an example of schema passed to refParser:

```
var json = [{
    "$uri": "/api/users/4",
    "controllers": [
        {"$ref": "/api/controllers/123"},
        {"$ref": "/api/controllers/456"},
        {"$ref": "/api/controllers/678"}
    ],
    "email": "a@b.c",
    "is_deleted": false,
    "is_super_admin": true,
    "is_verified": true
}, {
    "$uri": "/api/users/13",
    "controllers": [
        {"$ref": "/api/controllers/1233"},
        {"$ref": "/api/controllers/4231"}
    ],
    "email": "e@f.g",
    "is_deleted": false,
    "is_super_admin": false,
    "is_verified": true
}];
```

**Comment by BigstickCarpet** [comment]
Sorry I didn't get a chance to respond yesterday, but it looks like you've discovered what I was going to say anyway.   The trick is to pass the URL that you want (in your case `http://localhost:8888`) along with the schema object.

**Comment by dzuluaga** [comment]
Same problem here. I get this error `Error: ENOENT: no such file or directory, open '/Documents/tools/git/dir1/dir2/node/refs/parameters.json'` with a JSON file with a ref like this one below: 

```javascript
      "resources": {
        "collection": {
          "description": "A collection of Accounts.
          "parameters": [
            {
              "$ref": "./refs/parameters.json#/common/collection"
            },
            {
              "in": "query",
              "name": "customer",
              "description": "Only include customers (stage 6 in SFDC)",
              "required": false,
              "type": "boolean"
            }
...
```
The only way to workaround this issue is to move my refs directory to the current working directory or essentially, the root directory of my Node.js app, which I'm trying to avoid as it breaks a component-based structure. I'm also trying to avoid http protocol to fetch those files.

It'd be great if as part of the options, there was a way to specify a relative base.

BTW - Love the project!

**Comment by BigstickCarpet** [comment]
@dzuluaga - See my reply above.  You can specify the base URL as a parameter.

**Comment by dzuluaga** [comment]
Awesome @BigstickCarpet. It was a bit cryptic ;). But finally worked. Issue #13 gave me the clues. Here's my version of the above.

```javascript
  return $RefParser.dereference('./api/models/', './api/models/openapi-model.json', {})
      .then(function(dmResolved) {
        debug('data model resolved', dmResolved);
        return dmResolved;
      })
```
