### ISSUE TITLE
Root ref fails to parse

### ISSUE THREAD

**Issue by isaacl** [APIDevTools/json-schema-ref-parser#201]
```json
{
  "$ref": "#/definitions/EmailConfig",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "EmailConfig": {
      "additionalProperties": false,
      "properties": {
        "adminContact": {
          "type": "string"
        }
      }
    }
  }
}
```
is valid (in fact is part of the [test suite here](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/2019-09/tests/draft7/ref.json#L122-L129)).  But json-schema-to-typescript fails to resolve the ref using this library.

---------
Originally filed at bcherny/json-schema-to-typescript#349

**Comment by vinyasns** [comment]
@isaacl Yes I faced the same issue, it gives 'Circular $ref pointer found ...' error even though this is a valid case.

**Comment by philsturgeon** [comment]
If this is still an issue please can somebody send a pull request.
