### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [APIDevTools/json-schema-ref-parser#203]
Would you be okay with cutting a new release and putting it on NPM? I'd love to try out the new speed improvements that were recently added 🙂

**Comment by philsturgeon** [comment]
New release is coming. There's a few new maintainers around here and we're getting the appropriate permissions to the appropriate people.

**Comment by P0lip** [comment]
Hey @Bosch-Eli-Black.
A new version has just been released.
![image](https://user-images.githubusercontent.com/9273484/104904017-01c0d500-5981-11eb-9a6f-733319683f77.png)
