### ISSUE TITLE
Latest 9.0.7 seems to introduce indirect performance issues

### ISSUE THREAD

**Issue by nulltoken** [APIDevTools/json-schema-ref-parser#211]
:wave:

While upgrading some indirect dependencies, we've bumped into some performance regressions.

Running time `getHttpOperationsFromSpec` (from prism-cli) against the same large(15Mb+) openapi 3.x document, exposing 750+ endpoints, shows a great difference in execution duration, depending on the underlying `json-schema-ref-parser` version.

```
json-schema-ref-parser@9.0.6
Converting routing definition '2b45bad3192bfc652c94d60c869dab50f4d7a3bc' to Prism format: 748.239ms

json-schema-ref-parser@9.0.7
Converting routing definition '2b45bad3192bfc652c94d60c869dab50f4d7a3bc' to Prism format: 1:03.202 (m:ss.mmm)
```

I can consistently repro this on my side. Have you noticed a similar behavior on your side? Wouldn't that be the case, I could try and build up a repro case.

/cc @P0lip @XVincentX

**Comment by P0lip** [comment]
Hey!
I haven't observed that. In fact, #195 proved to be helpful in most scenarios we deal with.
There was no other meaningful change that could affect it.
BTW, did you try setting resolution to `@stoplight/json-schema-ref-parser`? 
We backported the above change with a few twists (IIRC).
Wondering what the result would be.

**Comment by nulltoken** [comment]
@P0lip Thanks for the feedback!

>BTW, did you try setting resolution to @stoplight/json-schema-ref-parser?

I've currently set my `package.json` resolution to 

```
"resolutions": {
    "@stoplight/prism-cli/json-schema-ref-parser": "9.0.6"
  },
```

I'm not sure to know the proper syntax in order to tweak the resolution so that it resolves to an entirely different package though. How should I do this?

**Comment by P0lip** [comment]
@nulltoken 
```json
"resolutions": {
  "@stoplight/prism-cli/json-schema-ref-parser": "stoplightio/json-schema-ref-parser"
}
```
this should work, I think.
It'll load directly from gh.

**Comment by nulltoken** [comment]
@P0lip Thanks. That didn't seem to help

With 
"resolutions": {
  "@stoplight/prism-cli/json-schema-ref-parser": "stoplightio/json-schema-ref-parser"
}
=> Converting routing definition '2b45bad3192bfc652c94d60c869dab50f4d7a3bc' to Prism format: 1:10.836 (m:ss.mmm)

With 
  "resolutions": {
    "@stoplight/prism-cli/json-schema-ref-parser": "9.0.6"
  },
=> Converting routing definition '2b45bad3192bfc652c94d60c869dab50f4d7a3bc' to Prism format: 752.841ms

I'll try to work on a repro case and submit it today.

**Comment by nulltoken** [comment]
@P0lip 

>I'll try to work on a repro case and submit it today.

Done. See https://github.com/nulltoken/json-schema-ref-parser-repro-case

_Note:_ As the processed endpoints are very basic, the difference in time isn't as significative as shown above, but still relevant enough to showcase the issue. 

First GitHub action workflow run (https://github.com/nulltoken/json-schema-ref-parser-repro-case/runs/1805714126?check_suite_focus=true)
```
Running json-schema-ref-parser v9.0.7
Converting to Prism format: 4.691s
Number of processed (basic) endpoints 600
```

Second GitHub action workflow run (https://github.com/nulltoken/json-schema-ref-parser-repro-case/runs/1805736569?check_suite_focus=true)
```
Running json-schema-ref-parser v9.0.6
Converting to Prism format: 368.197ms
Number of processed (basic) endpoints 600
```

**Comment by P0lip** [comment]
Thanks a lot!
I'll take a look to see what could cause this performance cliff.

**Comment by P0lip** [comment]
![image](https://user-images.githubusercontent.com/9273484/106750800-9a657f00-6628-11eb-82e8-0d4590c34322.png)
![image](https://user-images.githubusercontent.com/9273484/106750823-a3eee700-6628-11eb-81a9-2fafa68e0690.png)
Yeah, the diff is indeed massive.


@nulltoken, I put together a candidate fix for the issue.
https://github.com/stoplightio/json-schema-ref-parser/commit/55dee7ed978b734a1fd354e01197236b3eaa106c
I tested it against a few documents, and the regression seen in case of your document is gone, while the benefits of previous solutions are still preserved (perf on par with 9.0.7 for unaffected documents).

Could you test the commit above?

**Comment by nulltoken** [comment]
>@nulltoken, I put together a candidate fix for the issue.

@P0lip Wow! Thanks a lot for that. 

>I put together a candidate fix for the issue. stoplightio@55dee7e

Would you know if the yarn resolution mechanism would allow me to directly point at that commit?

**Comment by P0lip** [comment]
> Would you know if the yarn resolution mechanism would allow me to directly point at that commit?

```
  "resolutions": {
    "@stoplight/prism-cli/json-schema-ref-parser": "stoplightio/json-schema-ref-parser#slower-dereference"
  },
```
does the following work?

**Comment by nulltoken** [comment]
>does the following work?

@P0lip This fix works awesomely! 

Below what I'm seeing now when dealing with the initial use case:

```
Converting routing definition '2b45bad3192bfc652c94d60c869dab50f4d7a3bc' to Prism format: 781.798ms
Converting routing definition '2b45bad3192bfc652c94d60c869dab50f4d7a3bc' to Prism format: 820.296ms
Converting routing definition '2b45bad3192bfc652c94d60c869dab50f4d7a3bc' to Prism format: 850.51ms
Converting routing definition '2b45bad3192bfc652c94d60c869dab50f4d7a3bc' to Prism format: 741.779ms
Converting routing definition '2b45bad3192bfc652c94d60c869dab50f4d7a3bc' to Prism format: 754.58ms
Converting routing definition '2b45bad3192bfc652c94d60c869dab50f4d7a3bc' to Prism format: 830.158ms
```

**Comment by P0lip** [comment]
Nice, glad to hear that!
I suggest to stick to that resolution then until the upstream package.
You can also stay with 9.0.6 if that's okay.

**Comment by nulltoken** [comment]
>I suggest to stick to that resolution then until the upstream package.

Hey! Would you have any ETA for a new release of the upstream package?

**Comment by P0lip** [comment]
Hey, I have no ETA at the moment, but it's been a while since the last release, so you can expect a new one soon!
I'll let you know once it's out.

**Comment by nulltoken** [comment]
>[...] you can expect a new one soon!

@P0lip And how soon would be "soon"? ;-)

**Comment by nulltoken** [comment]
@P0lip Kind bump?

**Comment by philsturgeon** [comment]
GitHub Actions have been broken for quite some time, and despite me thinking I'd fixed them, they're back to being broken. This stops release from working. https://github.com/APIDevTools/json-schema-ref-parser/actions

If you can spot the cause let me know, I have had a few gos but am currently stumped (and off sick).

**Comment by philsturgeon** [comment]
Got it! @nulltoken let me know if 9.0.8 is working a little quicker.
