### ISSUE TITLE
Impossible to bundle a circular schema after dereferencing it

### ISSUE THREAD

**Issue by paztis** [APIDevTools/json-schema-ref-parser#219]
If a schema has circular ancestor, it is possible to dereference it
but if we want to re-reference it (for stringification for example), it is impossible to bundle it.

Tested in the unit tests with specs/circular/circular-indirect-ancestor.yaml

```
let parser = new $RefParser();
const schemaDeref = await parser.dereference(path.rel("specs/circular/circular-indirect-ancestor.yaml"));

const schema = await parser.bundle(schemaDeref);
```

This crashed with Maximum call stack in 2 places:
- in resolve-externals.js crawl function
easily fixable with this code:
```
function crawl (obj, path, $refs, options, ancestors = []) {
  let promises = [];

  if (obj && typeof obj === "object" && !ArrayBuffer.isView(obj)) {
    if ($Ref.isExternal$Ref(obj)) {
      promises.push(resolve$Ref(obj, path, $refs, options));
    }
    else if (ancestors.indexOf(obj) === -1) {
      const nextAncestors = [...ancestors, obj];
      for (let key of Object.keys(obj)) {
        let keyPath = Pointer.join(path, key);
        let value = obj[key];

        if ($Ref.isExternal$Ref(value)) {
          promises.push(resolve$Ref(value, keyPath, $refs, options));
        }
        else {
          promises = promises.concat(crawl(value, keyPath, $refs, options, nextAncestors));
        }
      }
    }
  }

  return promises;
}
```

- then in bundle.js in crawl function
here I don't know how to create new references in case of circular detection

**Comment by paztis** [comment]
I've create a PR with a new method **rereference** that exactly do this job in sync: #221

Cab you look at it ?

**Comment by paztis** [comment]
Hello

Any new about it ? Have you found any time to look at the PR ?

**Comment by philsturgeon** [comment]
Why would you dereference AND bundle?  I don't understand the use case so its hard to imagine a solution.

**Comment by paztis** [comment]
My ui is based over schemas. I need to use schemas everywhere, and don't
want to support reference in tons of places.

But my ui need also to save in session storage the schemas. And I cannot
serialize the without re-referencing them

Le jeu. 6 mai 2021 à 13:52, Phil Sturgeon ***@***.***> a
écrit :

**Comment by philsturgeon** [comment]
@paztis can you see if this works in 9.0.9? We've done a lot of work on making various circular scenarios work better.

**Comment by SebastienGllmt** [comment]
I ran into this as well on the latest version (11.9.3)

Given this schema

```json
{
  "$id": "recursive.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "label": {
      "anyOf": [
        {
          "type": "integer"
        }
      ]
    },
    "value": {
      "$ref": "recursive.json"
    }
  },
  "title": "RecursiveType",
  "type": "object"
}
```

## Crashes
```ts
console.log(util.inspect(await $Refparser.bundle(schemaObj), { depth: null }))
console.log(util.inspect(await $Refparser.dereference(schemaObj), { depth: null }))
```

## Works

```ts
console.log(util.inspect(await $Refparser.bundle(schemaObj), { depth: null }))
console.log(util.inspect(await $Refparser.dereference(schemaObj), { depth: null }))
```

## Thoughts

It's weird that just switching the order of the calls would crash. However, *usually* you wouldn't call both of these on the same object. The only reason I was doing this was to test the difference between the outputs of both options
