### ISSUE TITLE
When resolving $ref, fields beside the $ref are not ignored

### ISSUE THREAD

**Issue by matthchr** [APIDevTools/json-schema-ref-parser#232]
I have a JSON that looks like this:
```
"Thing": {
    "$ref": "#/definitions/FancyString",
    "description": "Some description"
},
...
"FancyString": {
    "type": "string",
    "description": "My actual description"
}
```

Obviously, this is awkward as there's a "collision" between the two description fields. When I use `$RefParser` to parse this document, the resulting JSON for `Thing` is:
```
"Thing": {
    "type": "string",
    "description": "Some description"
},
```

The `"My actual description"` seems to be lost/not transferred over. If there is instead no description alongside the `$ref` in `Thing`, everything works as expected and the other description is copied over.

I believe that this is in conflict with the JSON schema specs handling of `$ref` ([draft-pbryan-zyp-json-ref-03](https://datatracker.ietf.org/doc/html/draft-pbryan-zyp-json-ref-03#section-3)) which states:
>  The "$ref" string value contains a URI [RFC3986], which identifies
   the location of the JSON value being referenced.  It is an error
   condition if the string value does not conform to URI syntax rules.
   Any members other than "$ref" in a JSON Reference object SHALL be
   ignored.

Is the above behavior working as expected, or a bug?

**Comment by philsturgeon** [comment]
This has been valid JSON schema since draft 7 or 2019-09 I don’t remember which.
