### ISSUE TITLE
Can't resolve any reference to external schema

### ISSUE THREAD

**Issue by ThomasKuhlmann** [APIDevTools/json-schema-ref-parser#241]
Hi,

I am using https://github.com/bcherny/json-schema-to-typescript and keep running immediately into issues when trying to reference another JSON schema file. 

Right now I created two simple test files:

**project.json**
```
{
  "$id": "project",
  "type": "object",
  "properties": {
    "priority": { "$ref": "priority" }
  }
}
```

**priority.json**
```
{
  "$id": "priority",
  "type": "string",
  "default": "priority string"
}

```

I pretty much immediately get this error:
`'SyntaxError: Unable to resolve $ref pointer "/Users/thomaskuhlmann/Projects/kreelu/packages/backend/cloud/src/schemas/priority"`

The path is correct, and there aren't any further details anywhere - any suggestions on how to troubleshoot this one?

Much obliged!
Thomas

**Comment by philsturgeon** [comment]
This tool was not designed to resolve $id. The conversation is over here and it’s basically in need of a new tool which is not yet finished. #145
