### ISSUE TITLE
ESM Version

### ISSUE THREAD

**Issue by jogibear9988** [APIDevTools/json-schema-ref-parser#252]
could you also provide a ESM build in your package?
I'm haveing a frontend without using a bundler, only ESM modules.

You could add an extra directory in your nuget, like "esm" and then create a new property in your package.json, like:

"module": "..." and
"exports": { "requier": "...", "import":"..."}

**Comment by jogibear9988** [comment]
you could use esbuild for this... https://medium.com/geekculture/build-a-library-with-esbuild-23235712f3c

**Comment by philsturgeon** [comment]
Hey @jogibear9988, can you send over a pull request for this? I don't know what it means and this is an free open-source project powered by the community who use it! 🙌🏻

**Comment by philsturgeon** [comment]
@jogibear9988 this is currently almost working in #288.
