### ISSUE TITLE
No polyfills for node modules http and https with Webpack 5 (via CRA 5)

### ISSUE THREAD

**Issue by illume** [APIDevTools/json-schema-ref-parser#254]
Hello!

I upgraded to Create React App 5 recently, which newly uses Webpack 5.

Now Webpack 5 is not automagically doing polyfills for node modules anymore.

The errors are something like this (I cut out a lot of noise):
```
ERROR in ./node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/http.js 3:13-28
  Module not found: Error: Can't resolve 'http' in '/home/xxx/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers'
  If you want to include a polyfill, you need to:
          - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
          - install 'stream-http'

ERROR in ./node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/http.js 5:14-30
  Module not found: Error: Can't resolve 'https' in '/home/xxx/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers'
  If you want to include a polyfill, you need to:
    - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
    - install 'https-browserify'
```

Is it possible to make @apidevtools/json-schema-ref-parser work with browsers somehow?

**Comment by jabeloep** [comment]
I am having the same issue.

**Comment by busheezy** [comment]
same issue but with vite.

**Comment by YukiGibson** [comment]
This has been quite the rabbit hole, to fix it for now I followed the error and added the fallback in the `webpack.config.js`:
```
module.exports = {
  resolve: {
    fallback: {
      https: require.resolve("https-browserify"),
      http: require.resolve("stream-http")
    },
```
And then installed each of those using `npm install https-browserify` and `npm install stream-https`

**Comment by jabeloep** [comment]
webpack.config.js is only available if you eject, which is something we are trying not to do.
