### ISSUE TITLE
Urlencoding of `$defs`

### ISSUE THREAD

**Issue by fjd-anh** [APIDevTools/json-schema-ref-parser#262]
We use the Parser to bundle a JSON Schema. In this process references to definitions in `$defs` get encoded to `%24defs`.

Example: before bundling
```json
        "signature": {
          "$ref": "#/$defs/signature"
        },

```

after bundling
```json
              "signature": {
                "$ref": "#/properties/contentStructure/%24defs/signature"
              },
```

Unfortunately, the code generator won't eat the `%24`, so we have to uneconde it manually.

Is there a chance to avoid the encoding?

**Comment by JonasGroeger** [comment]
Note the notice in the readme file. https://github.com/APIDevTools/json-schema-ref-parser/issues/285

**Comment by jonluca** [comment]
I dont believe this is happening anymore on latest - let me know with an example if it is
