### ISSUE TITLE
Cannot use 'in' operator to search for 'generate' in [Circular ~.properties .fields.items.oneOf.0.properties.values.items.oneOf.4.properties .values.oneOf.1.properties.values.items]

### ISSUE THREAD

**Issue by Emdave10** [APIDevTools/json-schema-ref-parser#270]
Hello, please explain what this error means and why I keep getting this error when trying to generate sample data for a json schema with nested object refs with **oneOf** property. And can a possible fix to the problem be offered.

**Comment by philsturgeon** [comment]
Please provide more information and use a more standard bug report template. What are you doing, what are you expecting, reproduceable case, etc.
