### ISSUE TITLE
Package v9.0.9 is missing excludedPathMatcher functionality (that's documented on the website)

### ISSUE THREAD

**Issue by ericallam** [APIDevTools/json-schema-ref-parser#273]
As you can see in the repo, index.d.ts has the `excludedPathMatcher` property:

https://github.com/APIDevTools/json-schema-ref-parser/blob/main/lib/index.d.ts#L240

But if you download the NPM package (https://registry.npmjs.org/@apidevtools/json-schema-ref-parser/-/json-schema-ref-parser-9.0.9.tgz) you'll see that the property is missing. It looks like just a mistake when publishing the package most likely.

**Comment by ericallam** [comment]
Turns out it's not just the type, but also the functionality. deference.js in the package does not have the excludedPathMatcher functionality.

**Comment by philsturgeon** [comment]
@ericallam thank you for looking into this. Can you send over a PR when you get a minute?

**Comment by ericallam** [comment]
It's possible I was incorrect about this bug but maybe I'm just confused about how `bundle` should work. I'm going to investigate this further and post a new issue when I'm ready 👍
