### ISSUE TITLE
Improve compatibility with browser by using better APIs

### ISSUE THREAD

**Issue by fregante** [APIDevTools/json-schema-ref-parser#275]
The browser compatibility claimed by this package is only due to bundlers’ polyfills, which are increasingly missing:

- https://github.com/APIDevTools/json-schema-ref-parser/issues/257
- https://github.com/APIDevTools/json-schema-ref-parser/issues/254
- https://github.com/JS-DevTools/ono/issues/17
- https://github.com/APIDevTools/json-schema-ref-parser/issues/137
- https://github.com/APIDevTools/json-schema-ref-parser/issues/267
- https://github.com/APIDevTools/json-schema-ref-parser/blob/5d7f89527ea773cdd37583a3c7ab91ee3b1db5a9/lib/util/url.js#L25-L26
- https://github.com/APIDevTools/json-schema-ref-parser/blob/ce236698d79b29ebddd49722a50d0dd1fdc140ff/lib/util/url.js#L3

`http` and `https` can be replaced by `fetch`, which is available in [Node 18](https://nodejs.org/ja/blog/announcements/v18-release-announce/#new-globally-available-browser-compatible-apis) and can already be used everywhere with https://github.com/matthew-andrews/isomorphic-fetch. I think this would also avoid `Buffer` issues

URLs can be parsed with the `URL` constructor, available globally in Node 10.

They can all be replaced by their modern and cross-platform equivalents or they can use something like `globalThis.process?.platform` to ensure that they don't immediately fail when missing.

**Comment by philsturgeon** [comment]
Thank you, this makes for a great Epic for folks to work from. 

If anyone can take a swing at knocking out a few of these that sounds be hugely helpful. I’ll have a go at a few right now with a strong drink and see how far I get.

**Comment by cihad** [comment]
Maybe this help: https://stackblitz.com/edit/webpack-webpack-js-org-vcdpkp?file=src/index.js

**Comment by cihad** [comment]
Maybe this will help: https://stackblitz.com/edit/webpack-webpack-js-org-vcdpkp?file=src/index.js

**Comment by alanpoulain** [comment]
I've taken it, please wait for the PR when the Hacktoberfest starts :smile:

**Comment by paztis** [comment]
it seems node-fetch dependency recreate this issue.
How to compile it now for browsers in webpack ?
