### ISSUE TITLE
excludedPathMatcher is missing in latest npm package....

### ISSUE THREAD

**Issue by chaeron** [APIDevTools/json-schema-ref-parser#278]
I have the latest npm package 9.0.9 installed.  excludedPathMatcher functionality is missing in this version of the npm package.  Source was updated 6 months ago to include this but no new NPM package has been released since then.

Any chance of getting a new npm package out soon that will contain the implemented excludedPathMatcher functionality?

Thanks!

**Comment by deepakthankachan** [comment]
I second this. excludedPathMatcher would be really helpful @JamesMessinger @philsturgeon Would really appreciate if you guys could do a release of the new code. It hasn't been updated in like a year :(

**Comment by philsturgeon** [comment]
Thanks for the prod. I currently plan to release a new new version when https://github.com/APIDevTools/json-schema-ref-parser/pull/280 and/or https://github.com/APIDevTools/json-schema-ref-parser/pull/268 are merged.

**Comment by MorevM** [comment]
@philsturgeon hi, why this issue is closed?
[The latest NPM version still 9.0.9](https://www.npmjs.com/package/@apidevtools/json-schema-ref-parser) (published a year ago) and it's still has no such functionality.
Is there any chance this will be released? Can someone help somehow?
