### ISSUE TITLE
The v9.1.0 does not contain the latest code for the main branch 

### ISSUE THREAD

**Issue by WinjayYu** [APIDevTools/json-schema-ref-parser#292]
The #280 pull quest resolved some compatibility issues and merged into the main branch two months ago. For example:

> The main branch lib/util/url.js file line 3:
```
let isWindows = /^win/.test(globalThis.process?.platform),
```

However, the npm package v9.1.0 released on 16 days ago is not the same as above.
> The v9.1.0 verison lib/util/url.js file line 3: 
```
let isWindows = /^win/.test(process.platform),
```

So, please help to release a new version of the latest code on the main branch.

**Comment by philsturgeon** [comment]
v9.1.0 has appeared by magic and gummed up the works as semantic release now cannot release its own v9.1.0 which would have the changes. Trying to figure out wtf is to be done here but I do not want to be spending any time on this project anymore after begging for help for over a year.

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/67381/213790263-f276ba46-3ea2-4b06-a59c-b6cabbc91ba2.png">

Ideas on the back of a postcard.

**Comment by philsturgeon** [comment]
@sesam semantic release has been weird and broken since before that change, but everything seems to be ticking along fine now thanks to new maintain @jonluca fixing it up. Use 9.1.2.
