### ISSUE TITLE
Breaking Firebase Tools

### ISSUE THREAD

**Issue by Psycarlo** [APIDevTools/json-schema-ref-parser#301]
Trying to install `firebase-tools` globally in Github Actions and get this error

`@apidevtools/json-schema-ref-parser@9.1.1: The engine "node" is incompatible with this module. Expected version ">= 17". Got "16.19.0"`

*Using Node 16

**Comment by DStenvers** [comment]
Same issue here. Tried downgrading to an older version but did not work. Any help is greatly appreciated!

**Comment by DStenvers** [comment]
My solution was to tell yarn to ignore this using: 
_RUN yarn install --ignore-engines_
Not an award-winning one, but for now I can continue working.

**Comment by jamesmoschou** [comment]
v9.1.2 has been released and should revert the change. The GitHub action should now pick it up and work if you rerun it.
