### ISSUE TITLE
Many missing exported types since #300

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [APIDevTools/json-schema-ref-parser#307]
The rewrite in #300 caused many previously-exported types to no longer be exported. These types are important when trying to work with customizations to the library.

The two types that are most relevant to my work are `JSONSchema` and `FileInfo`. `JSONSchema` is important for naming inputs and outputs to several `$RefParser` methods, and `FileInfo` is needed to safely write custom parser plugins as exposed by `$RefParser`

**Comment by bcherny** [comment]
+1

There also seems to be a bunch of type errors. To repro, create a new directory, `npm init`, then `npm install json-schema-ref-parser`.

**Comment by jonluca** [comment]
Sorry about that, we export more types now in v11.2.2 and v11.2.4
