### ISSUE TITLE
Exclude in-file $ref definitions?

### ISSUE THREAD

**Issue by iq-dot** [APIDevTools/json-schema-ref-parser#31]
Is it possible to limit only the $ref resolutions to external files only? I wish to avoid references that are within the file itself.

i.e. ignore those '#/definitions/MyDef' lines which refer to definitions within the file itself.

Is this possible?

**Comment by BigstickCarpet** [comment]
Hi @iq-dot.  Sorry for the delayed response, but yes, this functionality is exactly what [the `bundle()` method](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/docs/ref-parser.md#bundleschema-options-callback) does.
