### ISSUE TITLE
Incorrect path resolving for absolut paths under windows

### ISSUE THREAD

**Issue by ScienceOfficer** [APIDevTools/json-schema-ref-parser#311]
Hello everyone,

unfortunately I noticed that the resolving of absolute paths under windows is not working for me. The code doesn't seem to recognize that a absolute path is entered and prepends another absolute path. 

I tracked the error down to this function (https://github.com/APIDevTools/json-schema-ref-parser/blob/main/lib/util/url.ts#L177). Both checks `hasProjectDir` and `hasProjectUri` evaluate to false as my api.yaml isn't part of this project. `projectDir` evaluates to `C:\Projekte\projectname\node_modules\@apidevtools\json-schema-ref-parser\dist\` in my setup but only `C:\Projekte\projectname` is shared between the library and the source code of the project. 

It would be great if the problem could be fixed!

Here is also the stacktrace where you can see, what happend to the absolute path.
```json
{
  "stack":"JSONParserError: Error opening file "C:\Projekte\projectname\node_modules\@apidevtools\json-schema-ref-parser\dist\C:\Projekte\projectname\dist\server\api.yaml" ENOENT: no such file or directory, open 'C:\Projekte\projectname\node_modules\@apidevtools\json-schema-ref-parser\dist\C:\Projekte\projectname\dist\server\api.yaml' at Object.<anonymous> (C:\Projekte\projectname\node_modules\@apidevtools\json-schema-ref-parser\dist\lib\resolvers\file.js:72:23) at Generator.throw (<anonymous>) at rejected (C:\Projekte\projectname\node_modules\@apidevtools\json-schema-ref-parser\dist\lib\resolvers\file.js:29:65)",
  "code":"ERESOLVER",
  "name":"ResolverError",
  "message":"Error opening file "C:\Projekte\projectname\node_modules\@apidevtools\json-schema-ref-parser\dist\C:\Projekte\projectname\dist\server\api.yaml" ENOENT: no such file or directory, open 'C:\Projekte\projectname\node_modules\@apidevtools\json-schema-ref-parser\dist\C:\Projekte\projectname\dist\server\api.yaml'",
  "source":"C:\Projekte\projectname\node_modules\@apidevtools\json-schema-ref-parser\dist\C:\Projekte\projectname\dist\server\api.yaml",
  "path":null,
  "ioErrorCode":"ENOENT",
  "footprint":"null+C:\Projekte\projectname\node_modules\@apidevtools\json-schema-ref-parser\dist\C:\Projekte\projectname\dist\server\api.yaml+ERESOLVER+Error opening file "C:\Projekte\projectname\node_modules\@apidevtools\json-schema-ref-parser\dist\C:\Projekte\projectname\dist\server\api.yaml" ENOENT: no such file or directory, open 'C:\Projekte\projectname\node_modules\@apidevtools\json-schema-ref-parser\dist\C:\Projekte\projectname\dist\server\api.yaml'"
}
```

Used version of apidevtools: `"@apidevtools/json-schema-ref-parser": "10.1.0"`

**Comment by jonluca** [comment]
Fixed in v10.1.0

**Comment by janiu-001** [comment]
i have the same error  with v10.1.0 

```
\.pnpm\\@apidevtools+json-schema-ref-parser@10.1.0\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\.\\packages\\elderly-care\\common\\s
rc\\apidocs\\openapi.json+ERESOLVER+Error opening file
````

**Comment by jonluca** [comment]
Apologies I meant 11, can you try latest?

**Comment by janiu-001** [comment]
@jonluca  thanks for your response, but i do not use the apidevtools+json-schema-ref-parser directly, i use the `openapi-typescript-codegen`, and it depend on the v10.1.0,
```
    "dependencies": {
        "@apidevtools/json-schema-ref-parser": "^11.1.0",
        "camelcase": "^6.3.0",
        "commander": "^11.1.0",
        "fs-extra": "^11.2.0",
        "handlebars": "^4.7.8"
    },
```

how can i do? By the way, i install the packages with pnpm

**Comment by BenCGI** [comment]
Can confirm 11er is working. Thanks for the fix!

@janiu-001 You can override the nested dependency via https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides
