### ISSUE TITLE
merge the resolved value and the original reference

### ISSUE THREAD

**Issue by wanghongcheng0302** [APIDevTools/json-schema-ref-parser#316]
Hi~ I have schema like this
```json
{
  "type": "object",
  "definitions": {
    "upload": {
      "s-props": {
        "a": "a"
      }
    }
  }
}
```
```json
{
  "type": "object",
  "properties": {
    "upload": {
      "$ref": "root.json#/definitions/upload",
      "s-props": {
        "b": "b"
      }
    }
  }
}
```
the original reference's-props replace the resolved value's-props
```json
{
    "type": "object",
    "properties":
    {
        "upload":
        {
            "s-props":
            {
                "b": "b"
            }
        }
    }
}
```
this may be caused by this code
<img width="654" alt="image" src="https://user-images.githubusercontent.com/47001880/230875559-b6844d35-f717-47bc-b349-5ca7ca541f72.png">

I think a better way is to merge the resolved value and the resolved value, rather than by replacing

this is my fix
```javascript
for (const key of Object.keys(resolvedValue)) {
  if (!(key in merged)) {
    // @ts-expect-error TS(7053): Element implicitly has an 'any' type because expre... Remove this comment to see the full error message
    merged[key] = resolvedValue[key];
  } else {
    // My Fix:
    // Object.assign(merged[key], resolvedValue[key])
  }
}
```

**Comment by VonNeuwomann** [comment]
Fixed result
```json
{
    "type": "object",
    "properties":
    {
        "upload":
        {
            "s-props":
            {
                "b": "b",
                "a": "a"
            }
        }
    }
}
```

**Comment by udamir** [comment]
$ref with sibling content is equal to 'allOf: [{$ref:"..."}, sibling]'. So to merge it correctly you can use [allOf-merge](https://github.com/udamir/allof-merge) tool

**Comment by jonluca** [comment]
I dont think Object.assign is a good solution, as it only works for top level properties. I'm open to using @udamir's library, but I'm not sure how to best integrate it. Calling `merge({allOf[$ref, resolvedValue]})` doesnt lead to expected values
