### ISSUE TITLE
Changelog for version 10.0.0 seems to be missing

### ISSUE THREAD

**Issue by Akkora** [APIDevTools/json-schema-ref-parser#319]
When updating to version 10.0.0 I was looking for the changelog, but couldn't find one.

I checked the following places:
1. https://github.com/APIDevTools/json-schema-ref-parser/releases
2. https://apitools.dev/json-schema-ref-parser/
3. If there is any markdown file tracking changes

Is there a place where the changes are tracked?

**Comment by jonluca** [comment]
There were some issues with v10 - however, I'd recommend just looking at the commits in the releases on github 

https://github.com/APIDevTools/json-schema-ref-parser/releases
