### ISSUE TITLE
Dereference allOf

### ISSUE THREAD

**Issue by brettstack** [APIDevTools/json-schema-ref-parser#32]
While we wait for v5, `allOf` is the best way to combine multiple schemas. It would be nice if there was an option which would dereference this for you. For now I'm going to try and use https://www.npmjs.com/package/json-schema-resolve-allof

**Comment by handrews** [comment]
> While we wait for v5

Note that JSON Schema draft 5 is out, but was a very minimal update and introduced some bugs.  It does not have a meta schema (we may or may not publish one given the problems with the draft).  We are working on getting draft 6 out (with a meta-schema) which you can [track here with this milestone](https://github.com/json-schema-org/json-schema-spec/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22draft-next+%28draft-6%29%22)

Draft 6 is not expected to address the open re-use questions, although we continue to discuss options and I hope to get some things into draft 7.  There's still a lot of debate, and we want to put out a usable draft 6 ASAP.
