### ISSUE TITLE
win32 not available when using webpack 5 and path-browserify polyfill

### ISSUE THREAD

**Issue by jsarman** [APIDevTools/json-schema-ref-parser#330]
https://github.com/APIDevTools/json-schema-ref-parser/blob/26d824b4b230f4ce2471f73401a4b6f7c7c67ac2/lib/util/convert-path-to-posix.ts#L10

win32 is not supported withe the path-browserify polyfill.  This currently causes a null failure.
Cannot read properties of null (reading 'sep')
    at convertPathToPosix (convert-path-to-posix.js:12:1)

**Comment by jonluca** [comment]
Fixed in v11.2.2
