### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by Jonneal3** [APIDevTools/json-schema-ref-parser#337]
<img width="1251" alt="Screenshot 2024-03-05 at 3 35 45 PM" src="https://github.com/APIDevTools/json-schema-ref-parser/assets/92951162/2bc8dbf5-f5ce-4269-ba20-c0158ac24d01">

Module not found: ESM packages (node-fetch) need to be imported. Use 'import' to reference the package instead.

Next 14
Apple silicon M2
Next Build 

Anyone running into this issue??

**Comment by jonluca** [comment]
What node version are you using? We didn't change anything with the build, although there was an async import of node-fetch in there

Can you try v11.2.2?

**Comment by Jonneal3** [comment]
@jonluca sure 1 sec let me try that now

**Comment by Jonneal3** [comment]
<img width="631" alt="Screenshot 2024-03-05 at 4 07 08 PM" src="https://github.com/APIDevTools/json-schema-ref-parser/assets/92951162/bf1bb7e7-8f2c-4a75-9198-57394187de1b">

Actually yes looks like I am currently using that version

**Comment by jonluca** [comment]
Did you bump the version to that? There's no references to node-fetch in the version 11.2.2. Can you try clearing your node modules and let me know if it still is happening?
