### ISSUE TITLE
Syntax erro - Pointers must begin with "#/"

### ISSUE THREAD

**Issue by MrRoyce** [APIDevTools/json-schema-ref-parser#42]
Hi there, I just started getting this error today.  Not sure what changed or how to fix it.

![json-schema-ref-parser-syntax-error](https://user-images.githubusercontent.com/252359/28273407-4fef1bfc-6adc-11e7-8f9b-6cb6ae444c53.png)

Any ideas?

**Comment by BigstickCarpet** [comment]
This error means that you have an invalid `$ref` somewhere in your schema.  Without actually seeing your schema, I can't get any more specific than that.

**Comment by n1ywb** [comment]
This is a valid bug; it violates the spec WRT internal links. Internal links are not necessarily JSON pointers.

    $ node -e 'require("json-schema-ref-parser").dereference({"$ref": "#bar", "definitions": {"bar": {"$id": "#bar"}}}).then(s=>console.log(s))'
    (node:17237) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): 
    SyntaxError: Invalid $ref pointer "bar". Pointers must begin with "#/"

    $ ajv -d <(echo null) -s <(echo '{"$ref": "#bar", "definitions": {"bar": {"$id": "#bar"}}}')
    /dev/fd/63 valid

ajv gets it right

See http://json-schema.org/latest/json-schema-core.html#rfc.section.9.2.1

**Comment by n1ywb** [comment]
as a stopgap the program could simply ignore internal refs. Not ideal but better than crashing.

**Comment by n1ywb** [comment]
Example dereferencing local refs 
```      _walkSchema(schema, accum) {
        return _.reduce(Object.entries(schema), (a, [k, v])=>{
          if (k === '$id') a.ids[v] = a.parent;
          k === '$ref' && a.refs.push(a.parent);
          if (v && typeof v == "object") {
            let oldParent = a.parent;
            a.parent = v;
            let r = this._walkSchema(v, a)
            a.parent = oldParent;
            return r;
          }
          return a;
        }, accum);
      }
      _derefLocal(schema) {
        let stuff = this._walkSchema(
          schema,
          {parent: schema, ids: {}, refs: []}
        );
        stuff.refs.forEach(ref=>{
          if (ref.$ref[0] === '#' && ref.$ref[1] !== '/') {
            _.assign(ref, stuff.ids[ref.$ref]);
            delete ref.$id;
            delete ref.$ref;
          }
        })
        console.log(stuff);
        return schema;
      }
```

**Comment by n1ywb** [comment]
this seems to duplicate https://github.com/BigstickCarpet/json-schema-ref-parser/issues/17

**Comment by BigstickCarpet** [comment]
I intend to support inline references in the next version of JSON Schema $Ref Parser, which I have already begun working on.  👍 

In the meantime, I will implement @n1ywb's stopgap recommendation of ignoring these references.

**Comment by iilei** [comment]
6.1.0 has the same bug

**Comment by jrnail23** [comment]
I think this might also be related to #136

**Comment by Envek** [comment]
Faced it today in 9.0.6 version.
