### ISSUE TITLE
Weird circular ref causes endless loop

### ISSUE THREAD

**Issue by JamesMessinger** [APIDevTools/json-schema-ref-parser#56]
Something weird about the [Bungie.net API](https://raw.githubusercontent.com/APIs-guru/openapi-directory/751d9c5f3d1eea8facf0b1bac67f9f0ac659359a/APIs/bungie.net/2.0.0/swagger.yaml) causes the `dereference()` method to spin forever in an endless loop.  I haven't had time to fully investigate why yet.

Code to reproduce the bug:
```javascript
jsonSchemaRefParser.dereference('https://api.apis.guru/v2/specs/bungie.net/2.0.0/swagger.yaml')
    .then(() => {
        console.log('this line will never execute');
    })
    .catch(() => {
        console.log('neither will this line');
    });
```

**Comment by BigstickCarpet** [comment]
[This Stripe API](https://github.com/APIs-guru/openapi-directory/blob/d6f44c0c5cc92c8e447dda9e5e5043b4163b3ffc/APIs/stripe.com/2017-08-15/swagger.yaml] does the same thing

**Comment by hipstersmoothie** [comment]
....and the one for my job :( bundle works though.

**Comment by mikestead** [comment]
I was having this issue with the more recent [Stripe spec](https://api.apis.guru/v2/specs/stripe.com/2020-08-27/openapi.json). After upgrading to release [v9.0.7](https://github.com/APIDevTools/json-schema-ref-parser/releases/tag/v9.0.7) it seems to be fixed. Specifically #195 may have fixed it.

I just tested https://api.apis.guru/v2/specs/bungie.net/2.0.0/swagger.json from the original comment and it also fails in 9.0.6 and works with 9.0.7.
