### ISSUE TITLE
Enhancement: Include a command-line version to use json-schema-ref-parser via CLI

### ISSUE THREAD

**Issue by shreyas-agnihotri** [APIDevTools/json-schema-ref-parser#65]
Include a command-line version with the npm package so that `json-schema-ref-parser` can be simply used via CLI. This will make it easier to use this tool via CICD/build systems and also eliminate the need for writing a wrapper js script to consume this functionality.

Something like:
```
json-schema-ref-parser bundle --dereference {infile} {outfile}
```

**Comment by RazzM13** [comment]
Apparently, albeit a bit buggy with YAML, there is already a CLI version that can *dereference* and utilizes `json-schema-parser` under the hood: [json-dereference-cli](https://github.com/davidkelley/json-dereference-cli).

However, as the name implies, it's functionality is limited to just dereferencing, it would be nice if it also had support for *bundle* as well as perhaps provide a list of all external references (i.e. $Refs.paths).

**Comment by BigstickCarpet** [comment]
Yeah, I do have plans to create a CLI for this project eventually.  I currently have [a CLI](https://github.com/BigstickCarpet/swagger-cli) that uses this project under the hood to do bundling, but it's tailored for Swagger, rather than _any_ JSON Schema document

**Comment by RazzM13** [comment]
Thank you very much for providing us with *swagger-cli*. In terms of features, it is precisely what I need and I was already using it for dereferencing a swagger definition prior to having the need to inline the aforementioned into an AWS SAM file however, *swagger-cli*  performs validation prior to deferencing and, I haven't seen an option of skipping that validation, therefore cannot be used to deference anything other than *Swagger* files.

**Comment by BigstickCarpet** [comment]
Yeah, Swagger-CLI will throw an error for anything other than Swagger 2.0 files.  So I definitely need to create a more generic JSON Schema CLI that isn't specific to Swagger files.

**Comment by RazzM13** [comment]
Despite my limited experience with NodeJS, I would love to give you a hand with that, that is if you're willing and can provide some insight into how you'd envision it done; perhaps similar to *swagger-cli* without support for validation or with support for validation via JSON-Schema (e.g. [ajv](https://github.com/epoberezkin/ajv)) and I believe it might be useful to provide a list of all external references (i.e. $Refs.paths).

**Comment by DanielHabenicht** [comment]
Although not using `json-schema-ref-parser` @redocly/openapi-cli just does what you wanted.

**Comment by philsturgeon** [comment]
Between swagger-cli and openapi-cli most people should have a solution for their needs.

**Comment by dtheodor** [comment]
Both swagger-cli and opeapi-cli are swagger specific

**Comment by philsturgeon** [comment]
@dtheodor despite the name so is this tool. It's not actually conforming to the JSON Schema $ref usage, its "JSON Schema as in OpenAPI Schema" so might as well have OpenAPI in the name. 

If you'd like to contribute a CLI it would not be a huge amount of work, but in general new functionality is not being worked on so you'd need to code that up, or wrap this up in your own CLI code locally, or use something else.
