### ISSUE TITLE
Expose information about extended Refs

### ISSUE THREAD

**Issue by GabrielCastro** [APIDevTools/json-schema-ref-parser#70]
When resolving references it would be useful to know when there is a schema that was an extended ref. Ie.

given the following schema
```javascript
{
    type: 'object',
    required: ['a'],
    properties: {
        a: {
            $ref: '#/definitions/typeA',
            description: 'a in obj as a'
        },
        b: {
            $ref: '#/definitions/typeA',
            description: 'a in obj as b'
        }
    },
    definitions: {
        typeA: {
            type: 'number',
            description: 'a in defs'
        }
    }
}
```

it produces the following dereferenced output. 

```
{
    type: 'object',
    required: ['a'],
    properties: {
        a: {
            description: 'a in obj as a',
            type: 'number'
        },
        b: {
            description: 'a in obj as b',
            type: 'number'
        }
    },
    definitions: {
        typeA: {
            type: 'number',
            description: 'a in defs'
        }
    }
}
```

There is no way for the consumer to know that properties `a` and `b` were once the same pointer

**Comment by BigstickCarpet** [comment]
What would you propose as a solution?

Keep in mind that `a` and `b` _aren't_ the same object.  They both simply get _some_ of their properties from the same object.

**Comment by ErikWittern** [comment]
@alan-cha and I are actually interested in the same thing. We would like to keep track of the original references in the resulting dereferenced object.

What if the user could provide an option to retain the original `$ref` property in addition to the dereferenced value? A consideration with this idea is that the resulting value may trigger additional, superfluous dereferencing in future processing.

Alternatively, what if the user could provide the name of a field to add to `a` and `b` that holds the original reference? E.g., if the user states that field to be `original-$ref`, the resulting data would be:

```
{
    type: 'object',
    required: ['a'],
    properties: {
        a: {
            description: 'a in obj as a',
            type: 'number',
            original-$ref: '#/definitions/typeA'
        },
        b: {
            description: 'a in obj as b',
            type: 'number',
            original-$ref: '#/definitions/typeA'
        }
    },
    definitions: {
        typeA: {
            type: 'number',
            description: 'a in defs'
        }
    }
}
```

**Comment by theogravity** [comment]
@luma commit in his fork seems to be what I'm looking for - is it possible to include that in mainline?

**Comment by luma** [comment]
Probably if it was cleaned up. The way I implemented it was a bit of a hack
and it had at least one undesirable side affect (I can't remember what it
is right now but I'll try and find my notes).

I don't have any time to work on it right now but you're welcome to pick up
the change and propose to upstream? Perhaps the maintainers could recommend
ways to clean up the implementation
