### ISSUE TITLE
Bundle references into definitions

### ISSUE THREAD

**Issue by mickdekkers** [APIDevTools/json-schema-ref-parser#72]
Let's say we have a schema that has external references to another schema's [definitions](https://spacetelescope.github.io/understanding-json-schema/structuring.html):

foo.json
```json
{
  "definitions": {
    "foo": {
      "properties": {
        "a": {
          "$ref": "./bar.json#/definitions/bar"
        },
        "b": {
          "$ref": "./bar.json#/definitions/bar"
        },
        "c": {
          "$ref": "./bar.json#/definitions/bar"
        }
      }
    }
  }
}
```

bar.json
```json
{
  "definitions": {
    "bar": {
      "properties": {
        "a": {
          "type": "string"
        },
        "b": {
          "type": "number",
          "maximum": 20
        }
      }
    }
  }
}
```

When using `parser.bundle('foo.json')` to bundle the external references, this is the resulting schema:
```json
{
  "definitions": {
    "foo": {
      "properties": {
        "a": {
          "properties": {
            "a": {
              "type": "string"
            },
            "b": {
              "type": "number",
              "maximum": 20
            }
          }
        },
        "b": {
          "$ref": "#/definitions/foo/properties/a"
        },
        "c": {
          "$ref": "#/definitions/foo/properties/a"
        }
      }
    }
  }
}
```

While this is a valid schema, it seems more straightforward to copy the definition for `bar` into `definitions`, especially if it is referenced in multiple places:
```json
{
  "definitions": {
    "foo": {
      "properties": {
        "a": {
          "$ref": "#/definitions/bar"
        },
        "b": {
          "$ref": "#/definitions/bar"
        },
        "c": {
          "$ref": "#/definitions/bar"
        }
      }
    },
    "bar": {
      "properties": {
        "a": {
          "type": "string"
        },
        "b": {
          "type": "number",
          "maximum": 20
        }
      }
    }
  }
}
```

Can this be done somehow?

**Comment by BigstickCarpet** [comment]
You can accomplish this by referencing `bar` in the `definitions` section, like this:

```json
{
  "definitions": {
    "foo": {
      "properties": {
        "a": {
          "$ref": "./bar.json#/definitions/bar"
        },
        "b": {
          "$ref": "./bar.json#/definitions/bar"
        },
        "c": {
          "$ref": "./bar.json#/definitions/bar"
        }
      }
    }
  }
  "bar": {
    "$ref": "./bar.json#/definitions/bar" 
  }
}
```

**Comment by aaronschwartz** [comment]
This ability is super helpful for creating files that are used by other class generator tools.

Are there any plans to have an option to create the shared definition entries automatically?

When maintaining multiple files, it's kind of hard to remember/enforce that the definition entry is created along with the other references. And if those references ever change you need to make sure to go update the definition entry as well.

**Comment by BigstickCarpet** [comment]
@aaronschwartz - The behavior you're asking for doesn't sound (to me) like it adheres to [the JSON Reference spec](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03).  I also can't think of any straightforward way to implement it.  

That said, if you can get it working, I'd be happy to review a PR.  As long as it doesn't break any existing functionality and is isolated to just the `bundle()` method, I think it'll be ok.

**Comment by dpopp07** [comment]
Adding my +1 here because the requested behavior is necessary for generating client libraries from a combined API definition. I also think it does adhere to the spec as far as I can tell, and results in a much cleaner result (in my opinion 🙂 ). I would love to see this as a configurable option in the `bundle()` method.

I will attempt to write up a PR in the next couple of weeks if I can find the time. Thanks for being open to it

**Comment by philsturgeon** [comment]
This is a commonly requested feature but rewriting your JSON Schema is not what this tool is about. We've implemented some custom logic to take on this opinionated rewrite at stoplight.io and maybe we can release this as another OSS tool, but this is working as expected.
