### ISSUE TITLE
Bundling a Schema with allOf resolves references to allOf instead of actual reference

### ISSUE THREAD

**Issue by krenor** [APIDevTools/json-schema-ref-parser#74]
```JSON
// Definitions File
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://127.0.0.1:8181/base/definitions.schema.json#",
  "name": "definitions",
  "type": "object",
  "definitions": {
    "auto_increment": {
      "type": "number",
      "minimum": 1
    }
  }
}

// Example Schema
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://127.0.0.1:8181/foo.schema.json",
  "name": "foo",
  "type": "object",
  "properties": {
    "foo": {
      "$ref": "http://127.0.0.1:8181/base/definitions.schema.json#/definitions/auto_increment"
    },
    "bar": {
      "$ref": "http://127.0.0.1:8181/base/definitions.schema.json#/definitions/auto_increment"
    }
  },
  "required": [
    "foo",
    "bar"
  ]
}

// Schema to be bundled
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "allOf": [
    {
      "properties": {
        "body": {
          "$ref": "http://localhost:8181/foo.schema.json"
        }
      }
    }
  ]
}
```

This results in the following schema via `bundle()`:
```JSON
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "allOf": [
    {
      "properties": {
        "body": {
          "$schema": "http://json-schema.org/draft-06/schema#",
          "$id": "http://127.0.0.1:8181/foo.schema.json",
          "name": "foo",
          "type": "object",
          "properties": {
            "foo": {
              "type": "number",
              "minimum": 1,
              "description": "Auto incrementing id."
            },
            "bar": {
              "$ref": "#/allOf/1/properties/body/properties/foo"
            }
          },
          "required": [
            "foo",
            "bar"
          ]
        }
      }
    }
  ]
}
```

Is this a case where `dereference` should be used instead of `bundle` because it doesn't support this or is this an actual bug regarding `bundle`?

**Comment by BigstickCarpet** [comment]
I'm not sure what the problem is here.  The output looks correct to me, but maybe I'm missing something. Can you post what you _expect_ the output to be?  Or explain what's wrong with the output above?

**Comment by krenor** [comment]
```
"bar": {
  "$ref": "#/allOf/1/properties/body/properties/foo"
}
```

This seems to be an invalid path.

**Comment by BigstickCarpet** [comment]
It seems like jsonschemavalidator.net shows an error for pretty much _any_ `$ref`.  Maybe it doesn't support JSON Pointers.  🤷‍♂️

The `$ref` path that's being generated by json-schema-ref-parser is valid according to the [JSON Pointer spec](https://tools.ietf.org/html/rfc6901)

**Comment by BigstickCarpet** [comment]
For my own future reference:  [issue reproduction](https://runkit.com/bigstickcarpet/5a8ad72f7b4b6f00122ba122)

**Comment by krenor** [comment]
I think it's an error due to my use-case. 

> The "$id" keyword defines a URI for the schema, and the base URI that other URI references within the schema are resolved against. 
[(Source)](https://tools.ietf.org/html/draft-handrews-json-schema-00#section-9.2)

By adding an `$id` to a subschema, I've reset the base URI for other URI references, which includes any use of $ref within the subschema and its children.

`$ref`: 

> ...Resolved against the current URI base, it identifies the URI of a schema to use.
[(Source)](https://tools.ietf.org/html/draft-handrews-json-schema-00#section-8

By changing the definition of `bar` to the following, the schema will be valid.

```json
"bar": {
  "$ref": "#/properties/foo"
}
```
