### ISSUE TITLE
Sync versions of dereference, bundle, etc...?

### ISSUE THREAD

**Issue by jwalton** [APIDevTools/json-schema-ref-parser#82]
Would you be interested in a PR that added synchronous versions of dereference, bundle, and friends?  Something along the lines of:

```js
$ref = $RefParser.resolveSync(schema, {
  files: {
    'http://foo.com/file.yaml': {type: 'object', ...},
    './foo.yaml': {definitions: {User: {type: 'object'}}}
  }
});
```

So you can supply all the file contents ahead of time?

**Comment by MikeTaylor** [comment]
YES YES YES YES YES!!!

**Comment by MikeTaylor** [comment]
In the mean time, I made this: https://github.com/MikeTaylor/json-schema-ref-parser-sync

I'm not proud of it, but it works. I hope it's of use to someone else.

**Comment by JamesMessinger** [comment]
Closing as a duplicate of Issue #14
