### ISSUE TITLE
How to see current path inside resolver?

### ISSUE THREAD

**Issue by qm3ster** [APIDevTools/json-schema-ref-parser#98]
How can I make a custom resolver for relative paths?
How do I see the path from which the `$ref` originates?

**Comment by qm3ster** [comment]
I'm on it. Should be on the `file` object, right, not as another param?
This way it's a non-breaking change too.

**Comment by BigstickCarpet** [comment]
Yup.  That's what I was thinking as well.  Thanks for helping out!  🥇 💯

**Comment by ziadsawalha** [comment]
@qm3ster - have you made any progress on this? I was thinking of tackling it this weekend as I need it too.

Any hints on which file(s) to look at - that would speed things up for me if you already know that.

**Comment by qm3ster** [comment]
@ziadsawalha no, sorry. I started, but I don't think I have that branch any more.

**Comment by qm3ster** [comment]
This is where the `file` object is created - https://github.com/APIDevTools/json-schema-ref-parser/blob/master/lib/parse.js#L29

**Comment by ziadsawalha** [comment]
Thanks @qm3ster. After digging into this a little it turns out the behavior I was looking for was already implemented correctly.

My issue turned out to be a bug in https://github.com/maxdome/swagger-combine where it resolved files in relation to cwd and not the file itself.

**Comment by philsturgeon** [comment]
Implemented in #124.
